const timelineData = [{
        time: "Day 1",
        desc: "Introduction to Unmanned Vehicle & Applications",
        date: "Lecture 1",
        dateDesc: "Workshop 1",
        descInDepth: "\nLecture - session 1 \n\n \tParticipants will get a fundamental grasp of unmanned vehicles and their applications in the context of the Fourth Industrial Revolution during this introductory lecture. The lecture presents an overview of unmanned vehicles, delving into its basic principles, components, and technology. Participants will understand the revolutionary possibilities of unmanned vehicles in various ways and an understanding of the revolutionary possibilities of unmanned vehicles in a variety of industries, including manufacturing, logistics, agriculture, and healthcare. Real-world examples and case studies will be provided to demonstrate the practical applications and advantages of unmanned vehicles in improving efficiency, productivity, and safety. Participants will have a greater understanding of the role of unmanned vehicles in the continuing industrial revolution and the opportunities they bring by the end of the lecture. \n\n\n Workshop - session 2 \n\n \tParticipants in this hands-on class will have the thrilling opportunity to design their very own unmanned vehicle from the ground up. The necessary components, such as the chassis, motors, sensors, and controllers, will be delivered to participants. Participants will assemble the vehicle, connect the electronic components, and learn about the fundamentals of vehicle construction and integration while being guided by teachers. Participants will have their own working unmanned vehicle by the end of the programme, ready for further exploration and development.",
    },
    {
        time: "Day 2",
        desc: "Object Detection & Recognition",
        date: "Lecture 2",
        dateDesc: "Workshop 2",
        descInDepth: "\nLecture - session 1  \n\n This session looks at the use of artificial intelligence and computer vision in unmanned vehicle object detection and recognition. Participants will learn about image and video processing techniques, as well as how AI algorithms enable object recognition. Feature extraction, object detection frameworks, and deep learning algorithms are among the topics discussed. Real-world examples demonstrate how object detection and recognition can be used in unmanned vehicles. Participants will grasp how AI-driven computer vision improves the perception and interpretation skills of unmanned vehicles by the end of the session. \n\n Workshop - session 2  \n\n On the following day,participants will focus on training their previously created car using object detection algorithms during this class. They will learn how to collect and annotate training data, prepare training data, and develop object detection algorithms using popular frameworks such as TensorFlow or PyTorch. Participants will experiment with several object identification models and methodologies, fine-tuning them to recognise specific objects or barriers important to their application. The goal is for the vehicle to be able to recognise and react to its surroundings on its own.",
    },
    {
        time: "Day 3",
        desc: "Navigation & route planning using AI",
        date: "Lecture 3",
        dateDesc: "Workshop 3",
        descInDepth: "\nLecture - session 1  \n\n This lecture focuses on AI-based navigation and route planning for unmanned vehicles. Participants will learn about vehicle localisation, mapping, and route optimisation using artificial intelligence approaches. GPS-based approaches, simultaneous localization and mapping (SLAM), and machine learning-based route planning are all covered. Real-world examples demonstrate the practical applications of AI in unmanned vehicle navigation. By the end of the lecture, listeners will grasp how AI improves autonomous navigation and enables effective route planning for unmanned vehicles.    \n\n Workshop - session 2  \n\n On the third day, participants will dive into mapping techniques for developing a robust navigation and route planning system. They will learn about simultaneous localization and mapping (SLAM) algorithms, which enable the vehicle to map its environment while simultaneously determining its own location within that map. Participants will explore different mapping sensors, such as LiDAR or camera-based systems, and work on implementing SLAM algorithms to generate accurate maps. The outcome will be a vehicle equipped with the ability to create and update maps for navigation purposes.In this workshop, participants will dive into mapping techniques for developing a robust navigation and route planning system. They will learn about simultaneous localization and mapping (SLAM) algorithms, which enable the vehicle to map its environment while simultaneously determining its own location within that map. Participants will explore different mapping sensors, such as LiDAR or camera-based systems, and work on implementing SLAM algorithms to generate accurate maps. The outcome will be a vehicle equipped with the ability to create and update maps for navigation purposes.",
    },
    {
        time: "Day 4",
        desc: "Autonomous Control using AI",
        date: "Lecture 4",
        dateDesc: "Workshop 4",
        descInDepth: "\nLecture - session 1  \n\n Participants in this lecture will study the use of artificial intelligence in autonomous control of unmanned vehicles. The goal is to enable vehicles to make autonomous judgements based on data collected from its sensors. The presentation covers AI decision-making algorithms and approaches such as path planning, obstacle avoidance, and behaviour modelling. Participants will discover how AI enables unmanned vehicles to analyse sensor data, perceive their surroundings, and take appropriate actions. To demonstrate the practical uses of AI in autonomous control, real-world case studies and examples will be discussed. Participants will grasp how AI enables unmanned vehicles to function autonomously and make logical judgements in a variety of settings by the end of the session.    \n\n Workshop - session 2  \n\n To the next following day, participants will focus on building a ground system to operate and control their unmanned vehicle autonomously. They will learn about various control algorithms, such as path planning, obstacle avoidance, and decision-making models. Participants will integrate the control system with the vehicle's sensors and actuators to enable autonomous operations. Through practical exercises, participants will develop the vehicle's ability to make its own decisions based on sensor data, navigate obstacles, and perform designated tasks with minimal human intervention.",
    },
    {
        time: "Day 5",
        desc: "Predictive maintenance and decision using AI",
        date: "Lecture 5",
        dateDesc: "Workshop 5",
        descInDepth: "\nLecture - session 1  \n\n The lecture focuses on the use of artificial intelligence in unmanned vehicle predictive maintenance and decision-making. Participants will learn how artificial intelligence algorithms analyse vehicle data to identify maintenance needs and maintain optimal vehicle health. Data collecting, processing, and machine learning techniques for proactive maintenance scheduling are presented. Real-world examples show how AI can be used in predictive maintenance. Participants will learn how AI enables proactive decision-making and maintenance planning, improving the reliability and longevity of autonomous vehicles by the end of the session.    \n\n Workshop - session 2  \n\n On the final day, participants will put the finishing touches on their unmanned vehicles to prepare them for competitions or real-world applications. They will refine the vehicle's control algorithms, optimize performance, and fine-tune any remaining issues. Participants will also have the opportunity to showcase their vehicles and share their experiences with their peers. The workshop will culminate in a friendly competition where participants can put their unmanned vehicles to the test, demonstrating their capabilities in completing specific tasks or challenges.",
    },
    
];

export default timelineData;